on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies.
      run: |
        sudo apt-get update -qy
        sudo apt install -y \
          python3 python3-dev python3-pip python3-venv python3-all \
          dh-python debhelper devscripts dput software-properties-common \
          python3-distutils python3-setuptools python3-wheel python3-stdeb python3-rich python3-pytest-mock
        python3 -m pip install .[scanner]
        python3 -m pip install .[agent]
        python3 -m pip install .
        python3 -m pip install -U setuptools setuptools_scm wheel google rich pytest_mock
    - run:
        python3 setup.py --command-packages=stdeb.command bdist_deb
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: deb_dist/*.deb