on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Init and update data submodule.
      run: |
        git submodule init
        git submodule update

    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install .[testing]
        pip install .[scanner]
        pip install .[agent]
        pip install pyinstaller

    - run: pyinstaller src/ostorlab/main.py

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*