on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[scanner]
        pip install .[agent]
        pip install pyinstaller

    - run: |
        pyinstaller --name oxo --debug=imports --onefile --add-data="./*:." --hidden-import alembic --hidden-import docker --hidden-import click --hidden-import py-ubjson --hidden-import nats-py --hidden-import Werkzeug --hidden-import aio-pika --hidden-import flask --hidden-import google-cloud-logging --hidden-import opentelemetry-distro --hidden-import opentelemetry-exporter-jaeger --hidden-import opentelemetry-exporter-gcp-trace --hidden-import psutil --hidden-import python-daemon src/ostorlab/main.py

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/*